# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from slam_msgs/ManipulatePosteriorGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class ManipulatePosteriorGoal(genpy.Message):
  _md5sum = "8b04f4e9d6ca23ba81a46ac8f4dc07f2"
  _type = "slam_msgs/ManipulatePosteriorGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
bool plot
bool sample
sensor_msgs/PointCloud2 pings
sensor_msgs/PointCloud2 track_position
sensor_msgs/PointCloud2 track_orientation

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field
"""
  __slots__ = ['plot','sample','pings','track_position','track_orientation']
  _slot_types = ['bool','bool','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       plot,sample,pings,track_position,track_orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ManipulatePosteriorGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.plot is None:
        self.plot = False
      if self.sample is None:
        self.sample = False
      if self.pings is None:
        self.pings = sensor_msgs.msg.PointCloud2()
      if self.track_position is None:
        self.track_position = sensor_msgs.msg.PointCloud2()
      if self.track_orientation is None:
        self.track_orientation = sensor_msgs.msg.PointCloud2()
    else:
      self.plot = False
      self.sample = False
      self.pings = sensor_msgs.msg.PointCloud2()
      self.track_position = sensor_msgs.msg.PointCloud2()
      self.track_orientation = sensor_msgs.msg.PointCloud2()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B3I().pack(_x.plot, _x.sample, _x.pings.header.seq, _x.pings.header.stamp.secs, _x.pings.header.stamp.nsecs))
      _x = self.pings.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.pings.height, _x.pings.width))
      length = len(self.pings.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.pings.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.pings.is_bigendian, _x.pings.point_step, _x.pings.row_step))
      _x = self.pings.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.pings.is_dense, _x.track_position.header.seq, _x.track_position.header.stamp.secs, _x.track_position.header.stamp.nsecs))
      _x = self.track_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.track_position.height, _x.track_position.width))
      length = len(self.track_position.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_position.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.track_position.is_bigendian, _x.track_position.point_step, _x.track_position.row_step))
      _x = self.track_position.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.track_position.is_dense, _x.track_orientation.header.seq, _x.track_orientation.header.stamp.secs, _x.track_orientation.header.stamp.nsecs))
      _x = self.track_orientation.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.track_orientation.height, _x.track_orientation.width))
      length = len(self.track_orientation.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_orientation.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.track_orientation.is_bigendian, _x.track_orientation.point_step, _x.track_orientation.row_step))
      _x = self.track_orientation.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.track_orientation.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pings is None:
        self.pings = sensor_msgs.msg.PointCloud2()
      if self.track_position is None:
        self.track_position = sensor_msgs.msg.PointCloud2()
      if self.track_orientation is None:
        self.track_orientation = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.plot, _x.sample, _x.pings.header.seq, _x.pings.header.stamp.secs, _x.pings.header.stamp.nsecs,) = _get_struct_2B3I().unpack(str[start:end])
      self.plot = bool(self.plot)
      self.sample = bool(self.sample)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pings.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pings.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.pings.height, _x.pings.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pings.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.pings.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.pings.is_bigendian, _x.pings.point_step, _x.pings.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.pings.is_bigendian = bool(self.pings.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.pings.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.pings.is_dense, _x.track_position.header.seq, _x.track_position.header.stamp.secs, _x.track_position.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.pings.is_dense = bool(self.pings.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.track_position.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.track_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.track_position.height, _x.track_position.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_position.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.track_position.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.track_position.is_bigendian, _x.track_position.point_step, _x.track_position.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.track_position.is_bigendian = bool(self.track_position.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.track_position.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.track_position.is_dense, _x.track_orientation.header.seq, _x.track_orientation.header.stamp.secs, _x.track_orientation.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.track_position.is_dense = bool(self.track_position.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.track_orientation.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.track_orientation.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.track_orientation.height, _x.track_orientation.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_orientation.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.track_orientation.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.track_orientation.is_bigendian, _x.track_orientation.point_step, _x.track_orientation.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.track_orientation.is_bigendian = bool(self.track_orientation.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.track_orientation.data = str[start:end]
      start = end
      end += 1
      (self.track_orientation.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.track_orientation.is_dense = bool(self.track_orientation.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B3I().pack(_x.plot, _x.sample, _x.pings.header.seq, _x.pings.header.stamp.secs, _x.pings.header.stamp.nsecs))
      _x = self.pings.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.pings.height, _x.pings.width))
      length = len(self.pings.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.pings.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.pings.is_bigendian, _x.pings.point_step, _x.pings.row_step))
      _x = self.pings.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.pings.is_dense, _x.track_position.header.seq, _x.track_position.header.stamp.secs, _x.track_position.header.stamp.nsecs))
      _x = self.track_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.track_position.height, _x.track_position.width))
      length = len(self.track_position.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_position.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.track_position.is_bigendian, _x.track_position.point_step, _x.track_position.row_step))
      _x = self.track_position.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.track_position.is_dense, _x.track_orientation.header.seq, _x.track_orientation.header.stamp.secs, _x.track_orientation.header.stamp.nsecs))
      _x = self.track_orientation.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.track_orientation.height, _x.track_orientation.width))
      length = len(self.track_orientation.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_orientation.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.track_orientation.is_bigendian, _x.track_orientation.point_step, _x.track_orientation.row_step))
      _x = self.track_orientation.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.track_orientation.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pings is None:
        self.pings = sensor_msgs.msg.PointCloud2()
      if self.track_position is None:
        self.track_position = sensor_msgs.msg.PointCloud2()
      if self.track_orientation is None:
        self.track_orientation = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.plot, _x.sample, _x.pings.header.seq, _x.pings.header.stamp.secs, _x.pings.header.stamp.nsecs,) = _get_struct_2B3I().unpack(str[start:end])
      self.plot = bool(self.plot)
      self.sample = bool(self.sample)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pings.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pings.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.pings.height, _x.pings.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pings.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.pings.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.pings.is_bigendian, _x.pings.point_step, _x.pings.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.pings.is_bigendian = bool(self.pings.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.pings.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.pings.is_dense, _x.track_position.header.seq, _x.track_position.header.stamp.secs, _x.track_position.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.pings.is_dense = bool(self.pings.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.track_position.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.track_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.track_position.height, _x.track_position.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_position.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.track_position.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.track_position.is_bigendian, _x.track_position.point_step, _x.track_position.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.track_position.is_bigendian = bool(self.track_position.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.track_position.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.track_position.is_dense, _x.track_orientation.header.seq, _x.track_orientation.header.stamp.secs, _x.track_orientation.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.track_position.is_dense = bool(self.track_position.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.track_orientation.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.track_orientation.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.track_orientation.height, _x.track_orientation.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_orientation.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.track_orientation.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.track_orientation.is_bigendian, _x.track_orientation.point_step, _x.track_orientation.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.track_orientation.is_bigendian = bool(self.track_orientation.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.track_orientation.data = str[start:end]
      start = end
      end += 1
      (self.track_orientation.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.track_orientation.is_dense = bool(self.track_orientation.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3I = None
def _get_struct_2B3I():
    global _struct_2B3I
    if _struct_2B3I is None:
        _struct_2B3I = struct.Struct("<2B3I")
    return _struct_2B3I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
