# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from slam_msgs/SamplePosteriorGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SamplePosteriorGoal(genpy.Message):
  _md5sum = "f901b2c1454b044728cdcd5b0d0944c8"
  _type = "slam_msgs/SamplePosteriorGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
int32 n
float64  xmin
float64  xmax
float64  ymin
float64  ymax
int32 subdivs
"""
  __slots__ = ['n','xmin','xmax','ymin','ymax','subdivs']
  _slot_types = ['int32','float64','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       n,xmin,xmax,ymin,ymax,subdivs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SamplePosteriorGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.n is None:
        self.n = 0
      if self.xmin is None:
        self.xmin = 0.
      if self.xmax is None:
        self.xmax = 0.
      if self.ymin is None:
        self.ymin = 0.
      if self.ymax is None:
        self.ymax = 0.
      if self.subdivs is None:
        self.subdivs = 0
    else:
      self.n = 0
      self.xmin = 0.
      self.xmax = 0.
      self.ymin = 0.
      self.ymax = 0.
      self.subdivs = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i4di().pack(_x.n, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.subdivs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.n, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.subdivs,) = _get_struct_i4di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i4di().pack(_x.n, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.subdivs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.n, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.subdivs,) = _get_struct_i4di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i4di = None
def _get_struct_i4di():
    global _struct_i4di
    if _struct_i4di is None:
        _struct_i4di = struct.Struct("<i4di")
    return _struct_i4di
