; Auto-generated. Do not edit!


(cl:in-package slam_msgs-msg)


;//! \htmlinclude ManipulatePosteriorFeedback.msg.html

(cl:defclass <ManipulatePosteriorFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ManipulatePosteriorFeedback (<ManipulatePosteriorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManipulatePosteriorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManipulatePosteriorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slam_msgs-msg:<ManipulatePosteriorFeedback> is deprecated: use slam_msgs-msg:ManipulatePosteriorFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManipulatePosteriorFeedback>) ostream)
  "Serializes a message object of type '<ManipulatePosteriorFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManipulatePosteriorFeedback>) istream)
  "Deserializes a message object of type '<ManipulatePosteriorFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManipulatePosteriorFeedback>)))
  "Returns string type for a message object of type '<ManipulatePosteriorFeedback>"
  "slam_msgs/ManipulatePosteriorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManipulatePosteriorFeedback)))
  "Returns string type for a message object of type 'ManipulatePosteriorFeedback"
  "slam_msgs/ManipulatePosteriorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManipulatePosteriorFeedback>)))
  "Returns md5sum for a message object of type '<ManipulatePosteriorFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManipulatePosteriorFeedback)))
  "Returns md5sum for a message object of type 'ManipulatePosteriorFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManipulatePosteriorFeedback>)))
  "Returns full string definition for message of type '<ManipulatePosteriorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManipulatePosteriorFeedback)))
  "Returns full string definition for message of type 'ManipulatePosteriorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManipulatePosteriorFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManipulatePosteriorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ManipulatePosteriorFeedback
))
