; Auto-generated. Do not edit!


(cl:in-package slam_msgs-msg)


;//! \htmlinclude MinibatchTrainingFeedback.msg.html

(cl:defclass <MinibatchTrainingFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MinibatchTrainingFeedback (<MinibatchTrainingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MinibatchTrainingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MinibatchTrainingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slam_msgs-msg:<MinibatchTrainingFeedback> is deprecated: use slam_msgs-msg:MinibatchTrainingFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MinibatchTrainingFeedback>) ostream)
  "Serializes a message object of type '<MinibatchTrainingFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MinibatchTrainingFeedback>) istream)
  "Deserializes a message object of type '<MinibatchTrainingFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MinibatchTrainingFeedback>)))
  "Returns string type for a message object of type '<MinibatchTrainingFeedback>"
  "slam_msgs/MinibatchTrainingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MinibatchTrainingFeedback)))
  "Returns string type for a message object of type 'MinibatchTrainingFeedback"
  "slam_msgs/MinibatchTrainingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MinibatchTrainingFeedback>)))
  "Returns md5sum for a message object of type '<MinibatchTrainingFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MinibatchTrainingFeedback)))
  "Returns md5sum for a message object of type 'MinibatchTrainingFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MinibatchTrainingFeedback>)))
  "Returns full string definition for message of type '<MinibatchTrainingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MinibatchTrainingFeedback)))
  "Returns full string definition for message of type 'MinibatchTrainingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MinibatchTrainingFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MinibatchTrainingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MinibatchTrainingFeedback
))
