; Auto-generated. Do not edit!


(cl:in-package slam_msgs-msg)


;//! \htmlinclude PlotPosteriorFeedback.msg.html

(cl:defclass <PlotPosteriorFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlotPosteriorFeedback (<PlotPosteriorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlotPosteriorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlotPosteriorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slam_msgs-msg:<PlotPosteriorFeedback> is deprecated: use slam_msgs-msg:PlotPosteriorFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlotPosteriorFeedback>) ostream)
  "Serializes a message object of type '<PlotPosteriorFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlotPosteriorFeedback>) istream)
  "Deserializes a message object of type '<PlotPosteriorFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlotPosteriorFeedback>)))
  "Returns string type for a message object of type '<PlotPosteriorFeedback>"
  "slam_msgs/PlotPosteriorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlotPosteriorFeedback)))
  "Returns string type for a message object of type 'PlotPosteriorFeedback"
  "slam_msgs/PlotPosteriorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlotPosteriorFeedback>)))
  "Returns md5sum for a message object of type '<PlotPosteriorFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlotPosteriorFeedback)))
  "Returns md5sum for a message object of type 'PlotPosteriorFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlotPosteriorFeedback>)))
  "Returns full string definition for message of type '<PlotPosteriorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlotPosteriorFeedback)))
  "Returns full string definition for message of type 'PlotPosteriorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback (not used)~%# std_msgs/bool feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlotPosteriorFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlotPosteriorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlotPosteriorFeedback
))
