; Auto-generated. Do not edit!


(cl:in-package slam_msgs-msg)


;//! \htmlinclude PlotPosteriorResult.msg.html

(cl:defclass <PlotPosteriorResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PlotPosteriorResult (<PlotPosteriorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlotPosteriorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlotPosteriorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slam_msgs-msg:<PlotPosteriorResult> is deprecated: use slam_msgs-msg:PlotPosteriorResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PlotPosteriorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader slam_msgs-msg:success-val is deprecated.  Use slam_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlotPosteriorResult>) ostream)
  "Serializes a message object of type '<PlotPosteriorResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlotPosteriorResult>) istream)
  "Deserializes a message object of type '<PlotPosteriorResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlotPosteriorResult>)))
  "Returns string type for a message object of type '<PlotPosteriorResult>"
  "slam_msgs/PlotPosteriorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlotPosteriorResult)))
  "Returns string type for a message object of type 'PlotPosteriorResult"
  "slam_msgs/PlotPosteriorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlotPosteriorResult>)))
  "Returns md5sum for a message object of type '<PlotPosteriorResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlotPosteriorResult)))
  "Returns md5sum for a message object of type 'PlotPosteriorResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlotPosteriorResult>)))
  "Returns full string definition for message of type '<PlotPosteriorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlotPosteriorResult)))
  "Returns full string definition for message of type 'PlotPosteriorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlotPosteriorResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlotPosteriorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlotPosteriorResult
    (cl:cons ':success (success msg))
))
