// Auto-generated. Do not edit!

// (in-package auv_model.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MbesSimFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.working = null;
    }
    else {
      if (initObj.hasOwnProperty('working')) {
        this.working = initObj.working
      }
      else {
        this.working = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MbesSimFeedback
    // Serialize message field [working]
    bufferOffset = _serializer.bool(obj.working, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MbesSimFeedback
    let len;
    let data = new MbesSimFeedback(null);
    // Deserialize message field [working]
    data.working = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'auv_model/MbesSimFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a910f77ef929028adc42d31381cbaa5b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    bool working
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MbesSimFeedback(null);
    if (msg.working !== undefined) {
      resolved.working = msg.working;
    }
    else {
      resolved.working = false
    }

    return resolved;
    }
};

module.exports = MbesSimFeedback;
