// Auto-generated. Do not edit!

// (in-package auv_model.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class SssSimGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.sss_pose = null;
      this.beams_num = null;
    }
    else {
      if (initObj.hasOwnProperty('sss_pose')) {
        this.sss_pose = initObj.sss_pose
      }
      else {
        this.sss_pose = new geometry_msgs.msg.TransformStamped();
      }
      if (initObj.hasOwnProperty('beams_num')) {
        this.beams_num = initObj.beams_num
      }
      else {
        this.beams_num = new std_msgs.msg.Int64();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SssSimGoal
    // Serialize message field [sss_pose]
    bufferOffset = geometry_msgs.msg.TransformStamped.serialize(obj.sss_pose, buffer, bufferOffset);
    // Serialize message field [beams_num]
    bufferOffset = std_msgs.msg.Int64.serialize(obj.beams_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SssSimGoal
    let len;
    let data = new SssSimGoal(null);
    // Deserialize message field [sss_pose]
    data.sss_pose = geometry_msgs.msg.TransformStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [beams_num]
    data.beams_num = std_msgs.msg.Int64.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.TransformStamped.getMessageSize(object.sss_pose);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'auv_model/SssSimGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1a2d1bc5f8b33dcbf8e4f2770989ed85';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    geometry_msgs/TransformStamped sss_pose
    std_msgs/Int64 beams_num
    
    ================================================================================
    MSG: geometry_msgs/TransformStamped
    # This expresses a transform from coordinate frame header.frame_id
    # to the coordinate frame child_frame_id
    #
    # This message is mostly used by the 
    # <a href="http://wiki.ros.org/tf">tf</a> package. 
    # See its documentation for more information.
    
    Header header
    string child_frame_id # the frame id of the child frame
    Transform transform
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Transform
    # This represents the transform between two coordinate frames in free space.
    
    Vector3 translation
    Quaternion rotation
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: std_msgs/Int64
    int64 data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SssSimGoal(null);
    if (msg.sss_pose !== undefined) {
      resolved.sss_pose = geometry_msgs.msg.TransformStamped.Resolve(msg.sss_pose)
    }
    else {
      resolved.sss_pose = new geometry_msgs.msg.TransformStamped()
    }

    if (msg.beams_num !== undefined) {
      resolved.beams_num = std_msgs.msg.Int64.Resolve(msg.beams_num)
    }
    else {
      resolved.beams_num = new std_msgs.msg.Int64()
    }

    return resolved;
    }
};

module.exports = SssSimGoal;
