// Generated by gencpp from file auv_model/MbesSimResult.msg
// DO NOT EDIT!


#ifndef AUV_MODEL_MESSAGE_MBESSIMRESULT_H
#define AUV_MODEL_MESSAGE_MBESSIMRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace auv_model
{
template <class ContainerAllocator>
struct MbesSimResult_
{
  typedef MbesSimResult_<ContainerAllocator> Type;

  MbesSimResult_()
    : sim_mbes()  {
    }
  MbesSimResult_(const ContainerAllocator& _alloc)
    : sim_mbes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _sim_mbes_type;
  _sim_mbes_type sim_mbes;





  typedef boost::shared_ptr< ::auv_model::MbesSimResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_model::MbesSimResult_<ContainerAllocator> const> ConstPtr;

}; // struct MbesSimResult_

typedef ::auv_model::MbesSimResult_<std::allocator<void> > MbesSimResult;

typedef boost::shared_ptr< ::auv_model::MbesSimResult > MbesSimResultPtr;
typedef boost::shared_ptr< ::auv_model::MbesSimResult const> MbesSimResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_model::MbesSimResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_model::MbesSimResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_model::MbesSimResult_<ContainerAllocator1> & lhs, const ::auv_model::MbesSimResult_<ContainerAllocator2> & rhs)
{
  return lhs.sim_mbes == rhs.sim_mbes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_model::MbesSimResult_<ContainerAllocator1> & lhs, const ::auv_model::MbesSimResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auv_model::MbesSimResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_model::MbesSimResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::MbesSimResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::MbesSimResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::MbesSimResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::MbesSimResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_model::MbesSimResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "022b09009b3ffffa6c2b71bd69d8f304";
  }

  static const char* value(const ::auv_model::MbesSimResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x022b09009b3ffffaULL;
  static const uint64_t static_value2 = 0x6c2b71bd69d8f304ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_model::MbesSimResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_model/MbesSimResult";
  }

  static const char* value(const ::auv_model::MbesSimResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_model::MbesSimResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"sensor_msgs/PointCloud2 sim_mbes\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::auv_model::MbesSimResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_model::MbesSimResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sim_mbes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MbesSimResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_model::MbesSimResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_model::MbesSimResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sim_mbes: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.sim_mbes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MODEL_MESSAGE_MBESSIMRESULT_H
