// Generated by gencpp from file auv_model/SssSimAction.msg
// DO NOT EDIT!


#ifndef AUV_MODEL_MESSAGE_SSSSIMACTION_H
#define AUV_MODEL_MESSAGE_SSSSIMACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <auv_model/SssSimActionGoal.h>
#include <auv_model/SssSimActionResult.h>
#include <auv_model/SssSimActionFeedback.h>

namespace auv_model
{
template <class ContainerAllocator>
struct SssSimAction_
{
  typedef SssSimAction_<ContainerAllocator> Type;

  SssSimAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  SssSimAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::auv_model::SssSimActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::auv_model::SssSimActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::auv_model::SssSimActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::auv_model::SssSimAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_model::SssSimAction_<ContainerAllocator> const> ConstPtr;

}; // struct SssSimAction_

typedef ::auv_model::SssSimAction_<std::allocator<void> > SssSimAction;

typedef boost::shared_ptr< ::auv_model::SssSimAction > SssSimActionPtr;
typedef boost::shared_ptr< ::auv_model::SssSimAction const> SssSimActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_model::SssSimAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_model::SssSimAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_model::SssSimAction_<ContainerAllocator1> & lhs, const ::auv_model::SssSimAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_model::SssSimAction_<ContainerAllocator1> & lhs, const ::auv_model::SssSimAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auv_model::SssSimAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_model::SssSimAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::SssSimAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::SssSimAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::SssSimAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::SssSimAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_model::SssSimAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9a1575f5243faf80bcb52afd54cfdee";
  }

  static const char* value(const ::auv_model::SssSimAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9a1575f5243faf8ULL;
  static const uint64_t static_value2 = 0x0bcb52afd54cfdeeULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_model::SssSimAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_model/SssSimAction";
  }

  static const char* value(const ::auv_model::SssSimAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_model::SssSimAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"SssSimActionGoal action_goal\n"
"SssSimActionResult action_result\n"
"SssSimActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: auv_model/SssSimActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"SssSimGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: auv_model/SssSimGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"geometry_msgs/TransformStamped sss_pose\n"
"std_msgs/Int64 beams_num\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64\n"
"int64 data\n"
"================================================================================\n"
"MSG: auv_model/SssSimActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SssSimResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: auv_model/SssSimResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"auv_model/Sidescan sim_sss\n"
"\n"
"================================================================================\n"
"MSG: auv_model/Sidescan\n"
"std_msgs/Header header\n"
"uint8   type          # Packet Type, 0xE2 = Sonar 8 Bit\n"
"uint32  time          # Ping time   [100 us]\n"
"uint8   frequency_id  # Freq Id, currently 0x00\n"
"int16   gain\n"
"uint16  decimation\n"
"float32 max_duration  # Max travel time of outermost bins (s)\n"
"uint8[] port_channel\n"
"uint8[] starboard_channel\n"
"uint8[] extra_channel\n"
"\n"
"================================================================================\n"
"MSG: auv_model/SssSimActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SssSimFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: auv_model/SssSimFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"bool working\n"
"\n"
;
  }

  static const char* value(const ::auv_model::SssSimAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_model::SssSimAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SssSimAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_model::SssSimAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_model::SssSimAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::auv_model::SssSimActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::auv_model::SssSimActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::auv_model::SssSimActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MODEL_MESSAGE_SSSSIMACTION_H
