// Generated by gencpp from file auv_model/SssSimGoal.msg
// DO NOT EDIT!


#ifndef AUV_MODEL_MESSAGE_SSSSIMGOAL_H
#define AUV_MODEL_MESSAGE_SSSSIMGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>
#include <std_msgs/Int64.h>

namespace auv_model
{
template <class ContainerAllocator>
struct SssSimGoal_
{
  typedef SssSimGoal_<ContainerAllocator> Type;

  SssSimGoal_()
    : sss_pose()
    , beams_num()  {
    }
  SssSimGoal_(const ContainerAllocator& _alloc)
    : sss_pose(_alloc)
    , beams_num(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _sss_pose_type;
  _sss_pose_type sss_pose;

   typedef  ::std_msgs::Int64_<ContainerAllocator>  _beams_num_type;
  _beams_num_type beams_num;





  typedef boost::shared_ptr< ::auv_model::SssSimGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_model::SssSimGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SssSimGoal_

typedef ::auv_model::SssSimGoal_<std::allocator<void> > SssSimGoal;

typedef boost::shared_ptr< ::auv_model::SssSimGoal > SssSimGoalPtr;
typedef boost::shared_ptr< ::auv_model::SssSimGoal const> SssSimGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_model::SssSimGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_model::SssSimGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_model::SssSimGoal_<ContainerAllocator1> & lhs, const ::auv_model::SssSimGoal_<ContainerAllocator2> & rhs)
{
  return lhs.sss_pose == rhs.sss_pose &&
    lhs.beams_num == rhs.beams_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_model::SssSimGoal_<ContainerAllocator1> & lhs, const ::auv_model::SssSimGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auv_model::SssSimGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_model::SssSimGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::SssSimGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_model::SssSimGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::SssSimGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_model::SssSimGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_model::SssSimGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a2d1bc5f8b33dcbf8e4f2770989ed85";
  }

  static const char* value(const ::auv_model::SssSimGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a2d1bc5f8b33dcbULL;
  static const uint64_t static_value2 = 0xf8e4f2770989ed85ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_model::SssSimGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_model/SssSimGoal";
  }

  static const char* value(const ::auv_model::SssSimGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_model::SssSimGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"geometry_msgs/TransformStamped sss_pose\n"
"std_msgs/Int64 beams_num\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64\n"
"int64 data\n"
;
  }

  static const char* value(const ::auv_model::SssSimGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_model::SssSimGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sss_pose);
      stream.next(m.beams_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SssSimGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_model::SssSimGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_model::SssSimGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sss_pose: ";
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.sss_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "beams_num: ";
    Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "  ", v.beams_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MODEL_MESSAGE_SSSSIMGOAL_H
