// Generated by gencpp from file slam_msgs/ManipulatePosteriorGoal.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_MANIPULATEPOSTERIORGOAL_H
#define SLAM_MSGS_MESSAGE_MANIPULATEPOSTERIORGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>

namespace slam_msgs
{
template <class ContainerAllocator>
struct ManipulatePosteriorGoal_
{
  typedef ManipulatePosteriorGoal_<ContainerAllocator> Type;

  ManipulatePosteriorGoal_()
    : plot(false)
    , sample(false)
    , pings()
    , track_position()
    , track_orientation()  {
    }
  ManipulatePosteriorGoal_(const ContainerAllocator& _alloc)
    : plot(false)
    , sample(false)
    , pings(_alloc)
    , track_position(_alloc)
    , track_orientation(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _plot_type;
  _plot_type plot;

   typedef uint8_t _sample_type;
  _sample_type sample;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pings_type;
  _pings_type pings;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _track_position_type;
  _track_position_type track_position;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _track_orientation_type;
  _track_orientation_type track_orientation;





  typedef boost::shared_ptr< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ManipulatePosteriorGoal_

typedef ::slam_msgs::ManipulatePosteriorGoal_<std::allocator<void> > ManipulatePosteriorGoal;

typedef boost::shared_ptr< ::slam_msgs::ManipulatePosteriorGoal > ManipulatePosteriorGoalPtr;
typedef boost::shared_ptr< ::slam_msgs::ManipulatePosteriorGoal const> ManipulatePosteriorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator1> & lhs, const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator2> & rhs)
{
  return lhs.plot == rhs.plot &&
    lhs.sample == rhs.sample &&
    lhs.pings == rhs.pings &&
    lhs.track_position == rhs.track_position &&
    lhs.track_orientation == rhs.track_orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator1> & lhs, const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b04f4e9d6ca23ba81a46ac8f4dc07f2";
  }

  static const char* value(const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b04f4e9d6ca23baULL;
  static const uint64_t static_value2 = 0x81a46ac8f4dc07f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/ManipulatePosteriorGoal";
  }

  static const char* value(const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"bool plot\n"
"bool sample\n"
"sensor_msgs/PointCloud2 pings\n"
"sensor_msgs/PointCloud2 track_position\n"
"sensor_msgs/PointCloud2 track_orientation\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plot);
      stream.next(m.sample);
      stream.next(m.pings);
      stream.next(m.track_position);
      stream.next(m.track_orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManipulatePosteriorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msgs::ManipulatePosteriorGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "plot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plot);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sample: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pings: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pings);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "track_position: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.track_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "track_orientation: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.track_orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_MANIPULATEPOSTERIORGOAL_H
