// Generated by gencpp from file slam_msgs/MinibatchTrainingActionGoal.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_MINIBATCHTRAININGACTIONGOAL_H
#define SLAM_MSGS_MESSAGE_MINIBATCHTRAININGACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <slam_msgs/MinibatchTrainingGoal.h>

namespace slam_msgs
{
template <class ContainerAllocator>
struct MinibatchTrainingActionGoal_
{
  typedef MinibatchTrainingActionGoal_<ContainerAllocator> Type;

  MinibatchTrainingActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  MinibatchTrainingActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::slam_msgs::MinibatchTrainingGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MinibatchTrainingActionGoal_

typedef ::slam_msgs::MinibatchTrainingActionGoal_<std::allocator<void> > MinibatchTrainingActionGoal;

typedef boost::shared_ptr< ::slam_msgs::MinibatchTrainingActionGoal > MinibatchTrainingActionGoalPtr;
typedef boost::shared_ptr< ::slam_msgs::MinibatchTrainingActionGoal const> MinibatchTrainingActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator1> & lhs, const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator1> & lhs, const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37f545f573520d94879866f5a3fde1f8";
  }

  static const char* value(const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37f545f573520d94ULL;
  static const uint64_t static_value2 = 0x879866f5a3fde1f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/MinibatchTrainingActionGoal";
  }

  static const char* value(const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"MinibatchTrainingGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: slam_msgs/MinibatchTrainingGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 particle_id \n"
"int32 mb_size\n"
;
  }

  static const char* value(const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MinibatchTrainingActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msgs::MinibatchTrainingActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::slam_msgs::MinibatchTrainingGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_MINIBATCHTRAININGACTIONGOAL_H
