// Generated by gencpp from file slam_msgs/PlotPosteriorResult.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_PLOTPOSTERIORRESULT_H
#define SLAM_MSGS_MESSAGE_PLOTPOSTERIORRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_msgs
{
template <class ContainerAllocator>
struct PlotPosteriorResult_
{
  typedef PlotPosteriorResult_<ContainerAllocator> Type;

  PlotPosteriorResult_()
    : success(false)  {
    }
  PlotPosteriorResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> const> ConstPtr;

}; // struct PlotPosteriorResult_

typedef ::slam_msgs::PlotPosteriorResult_<std::allocator<void> > PlotPosteriorResult;

typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorResult > PlotPosteriorResultPtr;
typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorResult const> PlotPosteriorResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator1> & lhs, const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator1> & lhs, const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/PlotPosteriorResult";
  }

  static const char* value(const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool success\n"
;
  }

  static const char* value(const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlotPosteriorResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::PlotPosteriorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msgs::PlotPosteriorResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_PLOTPOSTERIORRESULT_H
