// Generated by gencpp from file slam_msgs/PlotPosteriorFeedback.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_PLOTPOSTERIORFEEDBACK_H
#define SLAM_MSGS_MESSAGE_PLOTPOSTERIORFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_msgs
{
template <class ContainerAllocator>
struct PlotPosteriorFeedback_
{
  typedef PlotPosteriorFeedback_<ContainerAllocator> Type;

  PlotPosteriorFeedback_()
    {
    }
  PlotPosteriorFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PlotPosteriorFeedback_

typedef ::slam_msgs::PlotPosteriorFeedback_<std::allocator<void> > PlotPosteriorFeedback;

typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorFeedback > PlotPosteriorFeedbackPtr;
typedef boost::shared_ptr< ::slam_msgs::PlotPosteriorFeedback const> PlotPosteriorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/PlotPosteriorFeedback";
  }

  static const char* value(const ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback (not used)\n"
"# std_msgs/bool feedback\n"
"\n"
"\n"
;
  }

  static const char* value(const ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlotPosteriorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::slam_msgs::PlotPosteriorFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_PLOTPOSTERIORFEEDBACK_H
