// Generated by gencpp from file slam_msgs/ResampleRequest.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_RESAMPLEREQUEST_H
#define SLAM_MSGS_MESSAGE_RESAMPLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_msgs
{
template <class ContainerAllocator>
struct ResampleRequest_
{
  typedef ResampleRequest_<ContainerAllocator> Type;

  ResampleRequest_()
    : p_id(0)  {
    }
  ResampleRequest_(const ContainerAllocator& _alloc)
    : p_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _p_id_type;
  _p_id_type p_id;





  typedef boost::shared_ptr< ::slam_msgs::ResampleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::ResampleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResampleRequest_

typedef ::slam_msgs::ResampleRequest_<std::allocator<void> > ResampleRequest;

typedef boost::shared_ptr< ::slam_msgs::ResampleRequest > ResampleRequestPtr;
typedef boost::shared_ptr< ::slam_msgs::ResampleRequest const> ResampleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::ResampleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::ResampleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msgs::ResampleRequest_<ContainerAllocator1> & lhs, const ::slam_msgs::ResampleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.p_id == rhs.p_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msgs::ResampleRequest_<ContainerAllocator1> & lhs, const ::slam_msgs::ResampleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ResampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ResampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ResampleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b756527ae231c3b776634d9cac781fb9";
  }

  static const char* value(const ::slam_msgs::ResampleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb756527ae231c3b7ULL;
  static const uint64_t static_value2 = 0x76634d9cac781fb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/ResampleRequest";
  }

  static const char* value(const ::slam_msgs::ResampleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 p_id\n"
;
  }

  static const char* value(const ::slam_msgs::ResampleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResampleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::ResampleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msgs::ResampleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "p_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.p_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_RESAMPLEREQUEST_H
