// Generated by gencpp from file slam_msgs/ResampleResponse.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_RESAMPLERESPONSE_H
#define SLAM_MSGS_MESSAGE_RESAMPLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_msgs
{
template <class ContainerAllocator>
struct ResampleResponse_
{
  typedef ResampleResponse_<ContainerAllocator> Type;

  ResampleResponse_()
    : done(false)  {
    }
  ResampleResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::slam_msgs::ResampleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msgs::ResampleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResampleResponse_

typedef ::slam_msgs::ResampleResponse_<std::allocator<void> > ResampleResponse;

typedef boost::shared_ptr< ::slam_msgs::ResampleResponse > ResampleResponsePtr;
typedef boost::shared_ptr< ::slam_msgs::ResampleResponse const> ResampleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msgs::ResampleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msgs::ResampleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msgs::ResampleResponse_<ContainerAllocator1> & lhs, const ::slam_msgs::ResampleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msgs::ResampleResponse_<ContainerAllocator1> & lhs, const ::slam_msgs::ResampleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msgs::ResampleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msgs::ResampleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msgs::ResampleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::slam_msgs::ResampleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msgs/ResampleResponse";
  }

  static const char* value(const ::slam_msgs::ResampleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
"\n"
"\n"
;
  }

  static const char* value(const ::slam_msgs::ResampleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResampleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msgs::ResampleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msgs::ResampleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_RESAMPLERESPONSE_H
