// Generated by gencpp from file slam_msgs/Resample.msg
// DO NOT EDIT!


#ifndef SLAM_MSGS_MESSAGE_RESAMPLE_H
#define SLAM_MSGS_MESSAGE_RESAMPLE_H

#include <ros/service_traits.h>


#include <slam_msgs/ResampleRequest.h>
#include <slam_msgs/ResampleResponse.h>


namespace slam_msgs
{

struct Resample
{

typedef ResampleRequest Request;
typedef ResampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Resample
} // namespace slam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_msgs::Resample > {
  static const char* value()
  {
    return "1f80de1749f85c5c1e825039a9d7a2e4";
  }

  static const char* value(const ::slam_msgs::Resample&) { return value(); }
};

template<>
struct DataType< ::slam_msgs::Resample > {
  static const char* value()
  {
    return "slam_msgs/Resample";
  }

  static const char* value(const ::slam_msgs::Resample&) { return value(); }
};


// service_traits::MD5Sum< ::slam_msgs::ResampleRequest> should match
// service_traits::MD5Sum< ::slam_msgs::Resample >
template<>
struct MD5Sum< ::slam_msgs::ResampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_msgs::Resample >::value();
  }
  static const char* value(const ::slam_msgs::ResampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_msgs::ResampleRequest> should match
// service_traits::DataType< ::slam_msgs::Resample >
template<>
struct DataType< ::slam_msgs::ResampleRequest>
{
  static const char* value()
  {
    return DataType< ::slam_msgs::Resample >::value();
  }
  static const char* value(const ::slam_msgs::ResampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_msgs::ResampleResponse> should match
// service_traits::MD5Sum< ::slam_msgs::Resample >
template<>
struct MD5Sum< ::slam_msgs::ResampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_msgs::Resample >::value();
  }
  static const char* value(const ::slam_msgs::ResampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_msgs::ResampleResponse> should match
// service_traits::DataType< ::slam_msgs::Resample >
template<>
struct DataType< ::slam_msgs::ResampleResponse>
{
  static const char* value()
  {
    return DataType< ::slam_msgs::Resample >::value();
  }
  static const char* value(const ::slam_msgs::ResampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_MSGS_MESSAGE_RESAMPLE_H
