; Auto-generated. Do not edit!


(cl:in-package auv_model-msg)


;//! \htmlinclude SssSimFeedback.msg.html

(cl:defclass <SssSimFeedback> (roslisp-msg-protocol:ros-message)
  ((working
    :reader working
    :initarg :working
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SssSimFeedback (<SssSimFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SssSimFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SssSimFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name auv_model-msg:<SssSimFeedback> is deprecated: use auv_model-msg:SssSimFeedback instead.")))

(cl:ensure-generic-function 'working-val :lambda-list '(m))
(cl:defmethod working-val ((m <SssSimFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader auv_model-msg:working-val is deprecated.  Use auv_model-msg:working instead.")
  (working m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SssSimFeedback>) ostream)
  "Serializes a message object of type '<SssSimFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'working) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SssSimFeedback>) istream)
  "Deserializes a message object of type '<SssSimFeedback>"
    (cl:setf (cl:slot-value msg 'working) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SssSimFeedback>)))
  "Returns string type for a message object of type '<SssSimFeedback>"
  "auv_model/SssSimFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SssSimFeedback)))
  "Returns string type for a message object of type 'SssSimFeedback"
  "auv_model/SssSimFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SssSimFeedback>)))
  "Returns md5sum for a message object of type '<SssSimFeedback>"
  "a910f77ef929028adc42d31381cbaa5b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SssSimFeedback)))
  "Returns md5sum for a message object of type 'SssSimFeedback"
  "a910f77ef929028adc42d31381cbaa5b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SssSimFeedback>)))
  "Returns full string definition for message of type '<SssSimFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool working~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SssSimFeedback)))
  "Returns full string definition for message of type 'SssSimFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%bool working~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SssSimFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SssSimFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SssSimFeedback
    (cl:cons ':working (working msg))
))
