; Auto-generated. Do not edit!


(cl:in-package auv_model-msg)


;//! \htmlinclude SssSimResult.msg.html

(cl:defclass <SssSimResult> (roslisp-msg-protocol:ros-message)
  ((sim_sss
    :reader sim_sss
    :initarg :sim_sss
    :type auv_model-msg:Sidescan
    :initform (cl:make-instance 'auv_model-msg:Sidescan)))
)

(cl:defclass SssSimResult (<SssSimResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SssSimResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SssSimResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name auv_model-msg:<SssSimResult> is deprecated: use auv_model-msg:SssSimResult instead.")))

(cl:ensure-generic-function 'sim_sss-val :lambda-list '(m))
(cl:defmethod sim_sss-val ((m <SssSimResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader auv_model-msg:sim_sss-val is deprecated.  Use auv_model-msg:sim_sss instead.")
  (sim_sss m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SssSimResult>) ostream)
  "Serializes a message object of type '<SssSimResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'sim_sss) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SssSimResult>) istream)
  "Deserializes a message object of type '<SssSimResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'sim_sss) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SssSimResult>)))
  "Returns string type for a message object of type '<SssSimResult>"
  "auv_model/SssSimResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SssSimResult)))
  "Returns string type for a message object of type 'SssSimResult"
  "auv_model/SssSimResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SssSimResult>)))
  "Returns md5sum for a message object of type '<SssSimResult>"
  "d921a9c276522dee262b1eb9fb1fd6ba")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SssSimResult)))
  "Returns md5sum for a message object of type 'SssSimResult"
  "d921a9c276522dee262b1eb9fb1fd6ba")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SssSimResult>)))
  "Returns full string definition for message of type '<SssSimResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%auv_model/Sidescan sim_sss~%~%================================================================================~%MSG: auv_model/Sidescan~%std_msgs/Header header~%uint8   type          # Packet Type, 0xE2 = Sonar 8 Bit~%uint32  time          # Ping time   [100 us]~%uint8   frequency_id  # Freq Id, currently 0x00~%int16   gain~%uint16  decimation~%float32 max_duration  # Max travel time of outermost bins (s)~%uint8[] port_channel~%uint8[] starboard_channel~%uint8[] extra_channel~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SssSimResult)))
  "Returns full string definition for message of type 'SssSimResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%auv_model/Sidescan sim_sss~%~%================================================================================~%MSG: auv_model/Sidescan~%std_msgs/Header header~%uint8   type          # Packet Type, 0xE2 = Sonar 8 Bit~%uint32  time          # Ping time   [100 us]~%uint8   frequency_id  # Freq Id, currently 0x00~%int16   gain~%uint16  decimation~%float32 max_duration  # Max travel time of outermost bins (s)~%uint8[] port_channel~%uint8[] starboard_channel~%uint8[] extra_channel~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SssSimResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'sim_sss))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SssSimResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SssSimResult
    (cl:cons ':sim_sss (sim_sss msg))
))
