// Auto-generated. Do not edit!

// (in-package slam_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let sensor_msgs = _finder('sensor_msgs');

//-----------------------------------------------------------

class ManipulatePosteriorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.plot = null;
      this.sample = null;
      this.pings = null;
      this.track_position = null;
      this.track_orientation = null;
    }
    else {
      if (initObj.hasOwnProperty('plot')) {
        this.plot = initObj.plot
      }
      else {
        this.plot = false;
      }
      if (initObj.hasOwnProperty('sample')) {
        this.sample = initObj.sample
      }
      else {
        this.sample = false;
      }
      if (initObj.hasOwnProperty('pings')) {
        this.pings = initObj.pings
      }
      else {
        this.pings = new sensor_msgs.msg.PointCloud2();
      }
      if (initObj.hasOwnProperty('track_position')) {
        this.track_position = initObj.track_position
      }
      else {
        this.track_position = new sensor_msgs.msg.PointCloud2();
      }
      if (initObj.hasOwnProperty('track_orientation')) {
        this.track_orientation = initObj.track_orientation
      }
      else {
        this.track_orientation = new sensor_msgs.msg.PointCloud2();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ManipulatePosteriorGoal
    // Serialize message field [plot]
    bufferOffset = _serializer.bool(obj.plot, buffer, bufferOffset);
    // Serialize message field [sample]
    bufferOffset = _serializer.bool(obj.sample, buffer, bufferOffset);
    // Serialize message field [pings]
    bufferOffset = sensor_msgs.msg.PointCloud2.serialize(obj.pings, buffer, bufferOffset);
    // Serialize message field [track_position]
    bufferOffset = sensor_msgs.msg.PointCloud2.serialize(obj.track_position, buffer, bufferOffset);
    // Serialize message field [track_orientation]
    bufferOffset = sensor_msgs.msg.PointCloud2.serialize(obj.track_orientation, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ManipulatePosteriorGoal
    let len;
    let data = new ManipulatePosteriorGoal(null);
    // Deserialize message field [plot]
    data.plot = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [sample]
    data.sample = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [pings]
    data.pings = sensor_msgs.msg.PointCloud2.deserialize(buffer, bufferOffset);
    // Deserialize message field [track_position]
    data.track_position = sensor_msgs.msg.PointCloud2.deserialize(buffer, bufferOffset);
    // Deserialize message field [track_orientation]
    data.track_orientation = sensor_msgs.msg.PointCloud2.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += sensor_msgs.msg.PointCloud2.getMessageSize(object.pings);
    length += sensor_msgs.msg.PointCloud2.getMessageSize(object.track_position);
    length += sensor_msgs.msg.PointCloud2.getMessageSize(object.track_orientation);
    return length + 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'slam_msgs/ManipulatePosteriorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8b04f4e9d6ca23ba81a46ac8f4dc07f2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    bool plot
    bool sample
    sensor_msgs/PointCloud2 pings
    sensor_msgs/PointCloud2 track_position
    sensor_msgs/PointCloud2 track_orientation
    
    ================================================================================
    MSG: sensor_msgs/PointCloud2
    # This message holds a collection of N-dimensional points, which may
    # contain additional information such as normals, intensity, etc. The
    # point data is stored as a binary blob, its layout described by the
    # contents of the "fields" array.
    
    # The point cloud data may be organized 2d (image-like) or 1d
    # (unordered). Point clouds organized as 2d images may be produced by
    # camera depth sensors such as stereo or time-of-flight.
    
    # Time of sensor data acquisition, and the coordinate frame ID (for 3d
    # points).
    Header header
    
    # 2D structure of the point cloud. If the cloud is unordered, height is
    # 1 and width is the length of the point cloud.
    uint32 height
    uint32 width
    
    # Describes the channels and their layout in the binary data blob.
    PointField[] fields
    
    bool    is_bigendian # Is this data bigendian?
    uint32  point_step   # Length of a point in bytes
    uint32  row_step     # Length of a row in bytes
    uint8[] data         # Actual point data, size is (row_step*height)
    
    bool is_dense        # True if there are no invalid points
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: sensor_msgs/PointField
    # This message holds the description of one point entry in the
    # PointCloud2 message format.
    uint8 INT8    = 1
    uint8 UINT8   = 2
    uint8 INT16   = 3
    uint8 UINT16  = 4
    uint8 INT32   = 5
    uint8 UINT32  = 6
    uint8 FLOAT32 = 7
    uint8 FLOAT64 = 8
    
    string name      # Name of field
    uint32 offset    # Offset from start of point struct
    uint8  datatype  # Datatype enumeration, see above
    uint32 count     # How many elements in the field
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ManipulatePosteriorGoal(null);
    if (msg.plot !== undefined) {
      resolved.plot = msg.plot;
    }
    else {
      resolved.plot = false
    }

    if (msg.sample !== undefined) {
      resolved.sample = msg.sample;
    }
    else {
      resolved.sample = false
    }

    if (msg.pings !== undefined) {
      resolved.pings = sensor_msgs.msg.PointCloud2.Resolve(msg.pings)
    }
    else {
      resolved.pings = new sensor_msgs.msg.PointCloud2()
    }

    if (msg.track_position !== undefined) {
      resolved.track_position = sensor_msgs.msg.PointCloud2.Resolve(msg.track_position)
    }
    else {
      resolved.track_position = new sensor_msgs.msg.PointCloud2()
    }

    if (msg.track_orientation !== undefined) {
      resolved.track_orientation = sensor_msgs.msg.PointCloud2.Resolve(msg.track_orientation)
    }
    else {
      resolved.track_orientation = new sensor_msgs.msg.PointCloud2()
    }

    return resolved;
    }
};

module.exports = ManipulatePosteriorGoal;
